service: aws-python-simple-http-endpoint

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  currentTime:
    handler: handler.main
    events:
      - http:
          path: ping
          method: post
          response:
            headers:
              Content-Type: application/text